Initial Commit

diff --git a/build_spec.yaml b/build_spec.yaml
--- a/build_spec.yaml
+++ b/build_spec.yaml
@@ -16,17 +16,19 @@ steps:
     name: "Build container image"
     timeoutInSeconds: 3000
     command: |
-      set -x  
-
+      set -e  # Exit on any error
+      set -x  # Debug log commands
       
+      # Check Docker installation
+      docker --version
+
+      # Print environment variables for debugging
       echo "OCI_WORKSPACE_DIR: ${OCI_WORKSPACE_DIR}"
       echo "OCI_BUILD_RUN_ID: ${OCI_BUILD_RUN_ID}"
       echo "DOCKER_TAG: ${DOCKER_TAG}"
       echo "DEPLOYMENT_ENV: ${DEPLOYMENT_ENV}"
 
       export DEPLOYMENT_TIMEOUT="120s"
-      
-      
       export BUILDRUN_HASH=$(echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7)
       echo "BUILDRUN_HASH: ${BUILDRUN_HASH}"
 
@@ -39,8 +41,14 @@ steps:
       export IMAGE_VERSION="$(echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7)-${IMAGE_CREATED_BY}"
       export DOCKER_TAG="${REGISTRY}/${PROJECT_NAME}:${IMAGE_VERSION}"
 
-      
+      # Build Docker image
       docker build --progress=plain -t ${DOCKER_TAG} .
+
+      # Check Docker build success
+      if [ $? -ne 0 ]; then
+        echo "Docker build failed."
+        exit 1
+      fi
 
 
 
